### ISSUE TITLE
新公众号推送系统设计讨论整理

### ISSUE THREAD

**Issue by xihuanhh** [iyjian/dev-raven#7]
推送消息需求讨论

核心功能：
     用户通过某个地址能发送一条公众号模板消息，消息内容自定义, 这里有个疑问，是消息内容如果像github 事件这样，那接口是post 还是 get呢，还有参数名
可能需要针对不同推送地址，内部做一次各个webhook的内容参数转换地址

逻辑需求
1.  用户需要支持多个地址，同时地址支持手动过期，和私人地址，难点是私人地址如何实现鉴权
2. 用户可以接收别的用户地址接收到的消息推送

**Comment by xihuanhh** [comment]
目前基本框架已搭好，实现基本收消息和推送模板消息功能。

**Comment by iyjian** [comment]
1.用户需要支持多个地址，
实现方式： 具体如何操作达到这个效果

2.同时地址支持手动过期，
实现方式：

3.私人地址，
难点是私人地址如何实现鉴权，没明白啥叫私人地址。

4.用户可以接收别的用户地址接收到的消息推送
我任务这里应该是用户可以订阅其他用户的hook地址

**Comment by xihuanhh** [comment]
实现方式：

先确定数据库模型：
地址表

id | url | shorturl | isPrivate | whitelist | userid | expire
-- | -- | -- | -- | -- | -- | --

用户表  额外的一些信息暂时可以不考虑存储问题

id | openid | userkey | urllimits | isEnable
-- | -- | -- | -- | --

例如：


```
const user={
    id:1,
    openid:'o8A3psr3mIWX8QqonGZlBLmgUKoI',
    userkey: 'userkey',
    urllimits: 10,
    isEnable: true
}
// userkey 可以让用户修改，修改后原先的url都会鉴权失败而失效
// sha1  openid + userkey = 'esSzhjTXw7EIiiLEXc7tZmz9HLQ='
const urls =[{
        id:1,
        // 如果嫌这种url太low的话，可以暂时用这个，不然可能需要对应生成一个永久性的短连接地址作为替代
        url:'/1/esSzhjTXw7EIiiLEXc7tZmz9HLQ=/1',///{userId}/{shakey}/{urlId},
        shortUrl: '',
        isPrivate: false,
        whitelist: [127.0.0.1],
        userid: 1,
        expire: 2020-07-01 12:00:00
    },{
        id:2,
        url:'/1/esSzhjTXw7EIiiLEXc7tZmz9HLQ=/2',///{userId}/{shakey}/{urlId},
        shortUrl: '',
        isPrivate: false,
        whitelist: [127.0.0.1],
        userid: 1,
        expire: 2020-07-01 12:00:00
    }
]
//后端router实现

// 创建一条新链接记录,绑定过的user才能创建，为了安全接口需要频率设置
router.post('/api/v1/{userId}/urls')

// 实际的推送地址，可能为了url含义的隐藏，这个url会被转成一个短链接，数据库搜索到实际的url，也就下面这个接口，
// 进行真正的推送
router.get('/api/v1/1/esSzhjTXw7EIiiLEXc7tZmz9HLQ=/2/send')


// 订阅某个用户，如果订阅了，则能收到该用户下的hook地址收到的消息推送，
// 这个url上也可以加个标识，标识哪个url是可以被用户订阅的，用来控制url的订阅，而不是全部url消息都发送给订阅者
router.post('/api/v1/{userId}/follows')```

**Comment by xihuanhh** [comment]
订阅和取消实现：

### 订阅：

_订阅的前提应该是用户已经在我方系统进行注册，同时可以生成一个订阅码
/{userid}/{sha1}/{urlid}?followCode=要订阅用户的订阅码
根据该订阅码找到对应的用户，同时和要订阅的链接建立绑定关系_

### 取消订阅：

/{userid}/{sha1}/{urlid}?unfollow=要订阅用户的订阅码
根据该订阅码找到对应的用户，同时取消用户和该链接的绑定关系

**Comment by iyjian** [comment]
订阅的概念应该是  想要订阅的用户可以从公众号接受到被订阅方某个hook地址的消息推送   所以订阅的是地址，最好能订阅方点一下被订阅方的hook地址就可以完成订阅。
